name: Relatório PTAX Diário

on:
  schedule:
    - cron: "0 11 * * 1-5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: |
          pip install requests pandas openpyxl

      - name: Rodar script
        run: |
          python relatorio_ptax.py

      - name: Commitar Excel atualizado
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add relatorio_ptax.xlsx
          git commit -m "Atualização automática do relatório PTAX"
          git push
