def pegar_ptax(data):
    data_formatada = data.strftime("%m-%d-%Y")
    url = f"https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/odata/CotacaoDolarDia(dataCotacao=@dataCotacao)?@dataCotacao='{data_formatada}'&$top=100&$format=json"
    res = requests.get(url).json()
    df = pd.DataFrame(res.get("value", []))
    if df.empty:
        return None
    # Se a coluna 'horaCotacao' não existir, pega a primeira linha
    if "horaCotacao" in df.columns:
        ultima_cotacao = df.sort_values("horaCotacao").iloc[-1]
    else:
        ultima_cotacao = df.iloc[0]
    return {
        "Data": data,
        "Compra (PTAX)": ultima_cotacao.get("cotacaoCompra"),
        "Venda (PTAX)": ultima_cotacao.get("cotacaoVenda")
    }
